version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "${POSTGRES_DEV_PORT}:5432"
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      DB_PASSWORD: ${POSTGRES_PASSWORD}

  db-test:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8001:5432"
    environment:
      DB_PASSWORD: ${POSTGRES_PASSWORD}

  backend:
      build:
        context: backend
      ports:
        - "8000:8000"
      command: uvicorn backend.src.main:app --reload --host 0.0.0.0
      env_file:
        - .env
      volumes:
        - ./backend:/home/app/MoneySaver/backend
      depends_on:
        - db
        - redis
        - prometheus
        - grafana

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    expose:
      - "9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_volume:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasource.yml
      - grafana_volume:/var/lib/grafana
    env_file:
      - .env
    depends_on:
      - prometheus
    ports:
      - "8080:3000"

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    volumes:
      - redis_volume:/data

  redis-test:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "8002:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${TEST_REDIS_PASSWORD}
    env_file:
      - .env

  frontend:
    build:
      context:
        frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/home/app/MoneySaver/frontend/src
      - ./frontend/public:/home/app/MoneySaver/frontend/public
    depends_on:
      - backend




volumes:
  db_volume:
  prometheus_volume:
  grafana_volume:
  redis_volume: