version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "${POSTGRES_DEV_PORT}:5432"
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/postgres/data

  db-test:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8001:5432"

  backend:
      build:
        context: backend
      ports:
        - "8000:8000"
      command: uvicorn backend.src.main:app --reload --host 0.0.0.0
      env_file:
        - .env
      volumes:
        - ./backend:/home/app/MoneySaver/backend
      depends_on:
        - db

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    expose:
      - "9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasource.yml
    env_file:
      - .env
    depends_on:
      - prometheus
    ports:
      - "3000:3000"


volumes:
  db_volume:
