export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_PAGE_ROUTE = '/'
export const ACCOUNTS_ROUTE = '/accounts'
export const OPERATIONS_ROUTE = '/operations'