"""added to user model created_at and made default for is_active field

Revision ID: 689a4723a6f8
Revises: feb3428bd784
Create Date: 2022-12-10 21:53:19.544376

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '689a4723a6f8'
down_revision = 'feb3428bd784'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
