"""initial

Revision ID: 0ba19b81aee9
Revises: 
Create Date: 2022-11-16 21:41:42.239017

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0ba19b81aee9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('WALLET', 'BANK_ACCOUNT', name='accounttypes'), nullable=True),
    sa.Column('balance', sa.DECIMAL(), nullable=True),
    sa.Column('currency', sa.Enum('US', 'RUB', 'CNY', name='currencies'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('target_amount', sa.DECIMAL(), nullable=True),
    sa.Column('balance', sa.DECIMAL(), nullable=True),
    sa.Column('currency', sa.Enum('US', 'RUB', 'CNY', name='currencies'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spending_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('spending_limit', sa.DECIMAL(), nullable=True),
    sa.Column('limit_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal_spending',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receipt_account_id', sa.Integer(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(), nullable=True),
    sa.Column('currency', sa.Enum('US', 'RUB', 'CNY', name='currencies'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['receipt_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.Enum('US', 'RUB', 'CNY', name='currencies'), nullable=True),
    sa.Column('replenishment_account_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['replenishment_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spending',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('receipt_account_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(), nullable=True),
    sa.Column('currency', sa.Enum('US', 'RUB', 'CNY', name='currencies'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['spending_category.id'], ),
    sa.ForeignKeyConstraint(['receipt_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spending')
    op.drop_table('income')
    op.drop_table('goal_spending')
    op.drop_table('spending_category')
    op.drop_table('goal')
    op.drop_table('account')
    # ### end Alembic commands ###
