"""removed limit_duration in spending category, added spent_in_month

Revision ID: a75aa09a88cb
Revises: a3484157f3c4
Create Date: 2022-12-01 03:38:07.412056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a75aa09a88cb'
down_revision = 'a3484157f3c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spending_category', sa.Column('spent_in_month', sa.DECIMAL(), nullable=True))
    op.drop_column('spending_category', 'limit_duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spending_category', sa.Column('limit_duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('spending_category', 'spent_in_month')
    # ### end Alembic commands ###
