"""deleted_goal_spending_model

Revision ID: a3484157f3c4
Revises: 0ba19b81aee9
Create Date: 2022-11-25 03:23:38.032552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3484157f3c4'
down_revision = '0ba19b81aee9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal_spending')
    op.add_column('spending', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'spending', 'goal', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spending', type_='foreignkey')
    op.drop_column('spending', 'goal_id')
    op.create_table('goal_spending',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('receipt_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('currency', postgresql.ENUM('US', 'RUB', 'CNY', name='currencies'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], name='goal_spending_goal_id_fkey'),
    sa.ForeignKeyConstraint(['receipt_account_id'], ['account.id'], name='goal_spending_receipt_account_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='goal_spending_pkey')
    )
    # ### end Alembic commands ###
