"""made nullable=False for fields

Revision ID: 51636a59a55f
Revises: 689a4723a6f8
Create Date: 2022-12-17 00:07:39.162401

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51636a59a55f'
down_revision = '689a4723a6f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('account', 'type',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.alter_column('account', 'balance',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('account', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('account', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('account', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('goal', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('goal', 'target_amount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('goal', 'balance',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('goal', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('goal', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('income', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('income', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('income', 'replenishment_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('income', 'amount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('income', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('income', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('spending', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('spending', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('spending', 'receipt_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('spending', 'amount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('spending', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('spending', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('spending', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('spending_category', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('spending_category', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('spending_category', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('spending_category', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('spending', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('spending', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('spending', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('spending', 'amount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('spending', 'receipt_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('spending', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('spending', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('income', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('income', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('income', 'amount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('income', 'replenishment_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('income', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('income', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('goal', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('goal', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('goal', 'balance',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('goal', 'target_amount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('goal', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('account', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('account', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('account', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('account', 'balance',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('account', 'type',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.alter_column('account', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
