"""added amount_in_account_currency_at_creation for Income and Spending

Revision ID: a4a8dfa8c6e4
Revises: 51636a59a55f
Create Date: 2022-12-21 23:37:13.848285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a8dfa8c6e4'
down_revision = '51636a59a55f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income', sa.Column('amount_in_account_currency_at_creation', sa.DECIMAL(), nullable=False))
    op.add_column('spending', sa.Column('amount_in_account_currency_at_creation', sa.DECIMAL(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spending', 'amount_in_account_currency_at_creation')
    op.drop_column('income', 'amount_in_account_currency_at_creation')
    # ### end Alembic commands ###
