"""added is_active to account

Revision ID: a2f3c9b5ba3d
Revises: 3c650c4d368f
Create Date: 2022-12-06 03:15:09.371301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f3c9b5ba3d'
down_revision = '3c650c4d368f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'is_active')
    # ### end Alembic commands ###
