"""added category in spending

Revision ID: 2f4043437599
Revises: 4c0b54fcac7f
Create Date: 2023-01-07 20:22:29.910961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4043437599'
down_revision = '4c0b54fcac7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spending', sa.Column('category', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spending', 'category')
    # ### end Alembic commands ###
