"""removed spending limit from spending category model

Revision ID: cfbaa681d6ba
Revises: a4a8dfa8c6e4
Create Date: 2023-01-05 03:39:22.841523

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cfbaa681d6ba'
down_revision = 'a4a8dfa8c6e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('spending_category_user_id_fkey', 'spending_category', type_='foreignkey')
    op.drop_column('spending_category', 'spending_limit')
    op.drop_column('spending_category', 'user_id')
    op.drop_column('spending_category', 'spent_in_month')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spending_category', sa.Column('spent_in_month', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('spending_category', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('spending_category', sa.Column('spending_limit', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.create_foreign_key('spending_category_user_id_fkey', 'spending_category', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
